version: '3'
services:
  app:
    image: main-server:latest
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1q2w3e4r!
      - MYSQL_DATABASE=sakila
      - REDIS_HOST=redis

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r!
      - MYSQL_DATABASE=sakila
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
